# Happiness indicator?
## Could we correlate the human development index with people's happiness?

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
suicidemen_df=pd.read_csv("Documents/Nanodegree/DataAnalisys/InvestigateDataSet/suicide_men_per_100000_people.csv")
#Men mortality per 100,000 standard population, age adjusted and assuming all countries have same age composition, starting 1950
humandevelopment_df=pd.read_csv("Documents/Nanodegree/DataAnalisys/InvestigateDataSet/hdi_human_development_index.csv")
#Index to rank countries by level of "human development". It contains three dimensions: health, education and living standard

First of all, we have to know how data is in the files. The lenght of the columns to see if we can compare the files and differences among them.

In [3]:
humandevelopment_df.head(n=5)

,geo,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
0,Afghanistan,0.295,0.300,0.309,0.305,0.300,0.324,0.328,0.332,0.335,...,0.415,0.433,0.434,0.448,0.454,0.463,0.470,0.476,0.479,0.479
1,Albania,0.635,0.618,0.603,0.608,0.616,0.628,0.637,0.636,0.646,...,0.703,0.713,0.721,0.725,0.738,0.752,0.759,0.761,0.762,0.764
2,Algeria,0.577,0.581,0.587,0.591,0.595,0.600,0.609,0.617,0.627,...,0.690,0.697,0.705,0.714,0.724,0.732,0.737,0.741,0.743,0.745
3,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.819,0.819,0.843,0.850,0.857,0.858
4,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.454,0.468,0.480,0.488,0.495,0.508,0.523,0.527,0.531,0.533

In [4]:
suicidemen_df.head(n=5)

,geo,1950,1951,1952,1953,1954,1955,1956,1957,1958,...,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004
0,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.88
1,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.33
2,Algeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.14
3,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.05
4,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.50

Now we know there's a column named 'geo' in both files. We also know that there are differences in the time range. We'll now look closer to the 'geo' column in both data sets.

In [5]:
len(humandevelopment_df['geo'].unique())

187

In [6]:
len(suicidemen_df['geo'].unique())

190

We see there are some discrepancies and in order to make comparisons, we'll have to take this differencies into account. What are those differencies? Which countries are in the suicidemen_df data set and don't appear in the humandevelopment_df?

In [8]:
rowstodrop_df=suicidemen_df[~suicidemen_df.isin(humandevelopment_df)].dropna()

In [17]:
control=rowstodrop_df.index.tolist()

In [18]:
print control

[119, 120, 180, 181]

We'll have to drop those rows before merging the data sets

In [29]:
def reduce_df(df):
    rows=df.index.tolist()
    for i in rows:
        i=0
        if i<=len(rows):
            reduced_df=suicidemen_df.drop(suicidemen_df.index[rows[i]])
            i=i+1
        return reduced_df

In [30]:
reduce_df(rowstodrop_df)

,geo,1950,1951,1952,1953,1954,1955,1956,1957,1958,...,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004
0,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.880
1,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.330
2,Algeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.140
3,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.050
4,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.500
5,Antigua and Barbuda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.430
6,Argentina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.80,10.60,10.30,10.90,11.40,12.90,14.00,13.80,14.30,13.300
7,Armenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.390
8,Australia,13.9,14.30,16.00,15.9,16.20,15.5,16.0,17.9,19.10,...,18.10,20.40,21.60,21.60,20.10,18.70,18.90,17.50,16.00,15.500
9,Austria,NaN,NaN,NaN,NaN,NaN,30.0,29.4,31.3,30.90,...,29.60,29.10,25.70,25.60,24.20,25.10,23.40,25.10,22.30,22.400
10,Azerbaijan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.48,1.91,2.83,1.28,1.27,1.32,NaN,NaN,NaN,2.330
11,Bahamas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.240
12,Bahrain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.68,5.67,4.35,NaN,NaN,6.750
13,Bangladesh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.800
14,Barbados,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.560
15,Belarus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,53.60,NaN,58.50,59.40,56.90,58.50,55.00,54.30,56.40,57.200
16,Belgium,NaN,NaN,NaN,NaN,17.60,17.0,17.7,18.0,18.50,...,27.10,0.00,0.00,25.40,23.40,NaN,NaN,NaN,NaN,24.100
17,Belize,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.900
18,Benin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.960
19,Bhutan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.200
20,Bolivia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.970
21,Bosnia and Herzegovina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.300
22,Botswana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.500
23,Brazil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.53,7.54,7.70,7.56,7.02,7.05,7.82,7.42,7.54,7.460
24,Brunei,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.310
25,Bulgaria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.60,22.70,20.30,21.70,19.60,20.50,19.40,20.00,16.40,15.200
26,Burkina Faso,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.100
27,Burundi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.400
28,Cambodia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.980
29,Cameroon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.260
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,Sudan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.600
161,Suriname,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.600
162,Swaziland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.500
163,Sweden,NaN,22.80,23.80,25.1,22.60,24.0,27.6,27.5,22.70,...,18.30,16.90,16.60,16.70,16.50,15.10,15.60,16.30,14.50,15.600
164,Switzerland,NaN,30.30,31.00,33.0,32.60,29.9,30.6,30.6,30.10,...,25.20,25.10,23.80,0.00,0.00,0.00,21.90,22.40,19.10,18.700
165,Syria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.598
166,Tajikistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.260
167,Tanzania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.500
168,Thailand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.800
169,Timor-Leste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.300
170,Togo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.490
171,Tonga,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.850
172,Trinidad and Tobago,NaN,5.79,7.27,10.2,8.77,13.8,12.9,14.6,7.79,...,27.20,20.40,22.10,23.90,19.10,22.10,22.80,20.10,NaN,22.500
173,Tunisia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.330
174,Turkey,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.580
175,Turkmenistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.30,12.60,13.40,16.90,NaN,NaN,NaN,NaN,NaN,20.900
176,Tuvalu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.260
177,Uganda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.800
178,Ukraine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,46.50,48.80,47.40,46.90,46.00,46.50,43.20,41.10,40.40,37.400
179,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.810
180,United Kingdom,11.4,11.30,11.10,11.9,12.40,12.1,12.6,12.4,12.50,...,10.80,10.10,10.20,10.80,10.80,10.30,10.20,10.10,9.57,9.780
181,United States,17.8,16.30,15.90,16.2,16.40,16.2,16.0,15.8,17.30,...,18.70,18.10,17.50,17.30,16.40,15.90,16.30,16.50,16.10,16.200
182,Uruguay,NaN,NaN,NaN,NaN,NaN,18.0,21.2,17.1,18.10,...,20.40,19.40,22.60,25.50,22.10,27.90,23.20,NaN,NaN,24.600
183,Uzbekistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.90,15.50,13.60,13.50,14.10,14.40,13.80,10.80,9.56,8.340
184,Vanuatu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.260
185,Venezuela,NaN,NaN,NaN,NaN,NaN,11.7,12.5,10.3,12.40,...,NaN,9.18,9.02,9.40,10.00,10.30,10.60,9.73,8.30,7.210
186,Vietnam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.200
187,Yemen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.240
188,Zambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.500
189,Zimbabwe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.800